server:
  port: 80

socketio:
  host: 0.0.0.0
  port: 51888

northstar: 
  # 历史数据服务（需要购买用户授权）
  data-service:
    baseUrl: http://124.221.172.207:41888

logging:  level: 
    root: info
    '[tech.quantit.northstar]': debug
  file:    path: logs/
  
spring:
  redis:
    host: 127.0.0.1
    port: 6379
  profiles:
    active: ${env:prod}

---
spring:
  redis.database: 1
  config:    activate:      on-profile: prod
      
---
spring:
  redis.database: 1
  config:    activate:      on-profile: dev

---
spring:
  redis.database: 0
  config:    activate:      on-profile: test
      
---
spring:
  redis.database: 0
  config:
    activate:
      on-profile: e2e
