server:
  port: 8888
  servlet:
    context-path: /northstar

socketio:
  host: 127.0.0.1
  port: 51888

northstar: 
  auth:
    userId: ${nsuser:admin}
    password: ${nspwd:123456}
  contracts:
    canHandle: FUTURES
  holidays: 20210614,20210920,20210921

logging:
  level: 
    root: info
  path: logs/
  
spring:
  data:
      mongodb:
        uri: mongodb://127.0.0.1:27017/TEST_NS_DB
  mail:
    host: smtp.126.com
    username: some_email@126.com
    password: UQNXPDZJIYQTRFRW
    default-encoding: UTF-8
    subscribed: subscribed@anywhere.com
    port: 465
    protocol: smtp
    properties:
      mail:
        imap.ssl.socketFactory.fallback: false
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            socketFactory.class: com.fintech.modules.base.util.mail.MailSSLSocketFactory
        
        
