server:
  port: 8888
  servlet:
    context-path: /northstar

socketio:
  host: 127.0.0.1
  port: 51888

northstar: 
  auth:
    userId: ${nsuser:admin}
    password: ${nspwd:123456}
  contracts:
    canHandle: FUTURES
  holidays: 20210614,20210920,20210921,20211001,20211004,20211005,20211006,20211007

logging:
  level: 
    root: info
  path: logs/
  
spring:
  profiles:
    active: ${env:prod}
  mail:
    host: smtp.126.com
    username: ${email:somemail@126.com}
    password: UQNXPDZJIYQTRFRW
    default-encoding: UTF-8
    subscribed: ${sub_email:somemail@126.com}
    port: 465
    protocol: smtp
    properties:
      mail:
        imap.ssl.socketFactory.fallback: false
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            socketFactory.class: com.fintech.modules.base.util.mail.MailSSLSocketFactory
---
spring:
  profiles: prod
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/NS_DB
      
---
spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/NS_DB

---
spring:
  profiles: test
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/TEST_NS_DB
