server:
  port: 8888
  servlet:
    context-path: /northstar

socketio:
  host: 127.0.0.1
  port: 51888

northstar: 
  auth:
    userId: ${nsuser:admin}
    password: ${nspwd:123456}

logging:  level: 
    root: info
    '[tech.quantit.northstar]': debug
    '[tech.quantit.northstar.strategy.policy.signal]': trace
    #'[tech.quantit.northstar.strategy]': debug
  file:    path: logs/
  
spring:
  profiles:
    active: ${env:prod}
  mail:
    host: ${smtpHost}
    username: ${email}
    password: ${secret}
    default-encoding: UTF-8
    port: 465
    protocol: smtp
    properties:
      mail:
        imap.ssl.socketFactory.fallback: false
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            socketFactory.class: com.fintech.modules.base.util.mail.MailSSLSocketFactory
---
spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/NS_DB  config:    activate:      on-profile: prod
      
---
spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/NS_DB  config:    activate:      on-profile: dev

---
spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/TEST_NS_DB  config:    activate:      on-profile: test
