server:
  ssl:
    key-alias: northstar
    key-store-type: PKCS12
    key-store: classpath:keystore/northstarKeyStore.p12
    key-store-password: northstar666
northstar: 
  contraceDefFile: classpath:ContractDefinition.csv
  data-service:
    baseUrl: https://service.quantit.tech:44388
    w3BaseUrl: http://localhost
    
logging:
  level: 
    root: info
  file:
    path: logs/
  
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  profiles:
    active: ${env:dev}

---
server:
  port: 443
  ssl:
    enabled: true
  servlet:
    session:
      cookie:
        same-site: none
        secure: true
spring:
  config:
    activate:
      on-profile: prod
      
---
server:
  port: 80
  ssl:
    enabled: false
spring:
  config:
    activate:
      on-profile: dev

---
server:
  port: 80
  ssl:
    enabled: false
spring:
  config:
    activate:
      on-profile: test
      
---
server:
  port: 443
  ssl:
    enabled: true
  servlet:
    session:
      cookie:
        same-site: none
        secure: true
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  config:
    activate:
      on-profile: e2e
