server:
  port: 8888
  servlet:
    context-path: /northstar

socketio:
  host: 127.0.0.1
  port: 51888

northstar: 
  auth:
    userId: admin
    password: 123456
  contracts:
    canHandle: FUTURES

logging:
  level: 
    root: info
  path: logs/
  
spring:
  profiles:
    active: ${env:prod}
  data:
      mongodb:
        uri: mongodb://127.0.0.1:27017/NS_DB

        
        
