server:
  port: 443
  ssl:
    enabled: true    key-alias: northstar
    key-store-type: PKCS12
    key-store: classpath:keystore/northstarKeyStore.p12
    key-store-password: northstar666
  servlet:    session:      cookie:        same-site: none
        secure: true
        

northstar: 
  contraceDefFile: classpath:ContractDefinition.csv
  data-service:
    baseUrl: https://service.quantit.tech:44388

logging:  level: 
    root: info
    # 行情数据入口
    '[xyz.redtorch.gateway.ctp.x64v6v3v15v]': info
    # 行情数据出口
    '[tech.quantit.northstar.main.handler.broadcast]': info
    # K线数据验证
    '[tech.quantit.northstar.gateway.api.domain]': info
  file:    path: logs/
  
spring:
  redis:
    host: 127.0.0.1
    port: 6379
  profiles:
    active: ${env:prod}

---
spring:
  redis.database: 1
  config:    activate:      on-profile: prod
      
---
spring:
  redis.database: 1
  config:    activate:      on-profile: dev

---
spring:
  redis.database: 0
  config:    activate:      on-profile: test
      
---
spring:
  redis.database: 0
  config:
    activate:
      on-profile: e2e
