// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core_enum_chanlun.proto

package tech.quantit.northstar.strategy.api.utils.pb;

public final class ChanEnum {
  private ChanEnum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 网关类型
   * </pre>
   *
   * Protobuf enum {@code xyz.redtorch.pb.DirEnum}
   */
  public enum DirEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DIR_0 = 0;</code>
     */
    DIR_0(0),
    /**
     * <code>DIR_UP = 1;</code>
     */
    DIR_UP(1),
    /**
     * <code>DIR_DN = -1;</code>
     */
    DIR_DN(-1),
    /**
     * <pre>
     *下包含
     * </pre>
     *
     * <code>DIR_XBH = -2;</code>
     */
    DIR_XBH(-2),
    /**
     * <pre>
     *上包含
     * </pre>
     *
     * <code>DIR_SBH = 2;</code>
     */
    DIR_SBH(2),
    /**
     * <pre>
     * 不存在缺口
     * </pre>
     *
     * <code>QK_N = -3;</code>
     */
    QK_N(-3),
    /**
     * <pre>
     *存在缺口
     * </pre>
     *
     * <code>QK_Y = 3;</code>
     */
    QK_Y(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DIR_0 = 0;</code>
     */
    public static final int DIR_0_VALUE = 0;
    /**
     * <code>DIR_UP = 1;</code>
     */
    public static final int DIR_UP_VALUE = 1;
    /**
     * <code>DIR_DN = -1;</code>
     */
    public static final int DIR_DN_VALUE = -1;
    /**
     * <pre>
     *下包含
     * </pre>
     *
     * <code>DIR_XBH = -2;</code>
     */
    public static final int DIR_XBH_VALUE = -2;
    /**
     * <pre>
     *上包含
     * </pre>
     *
     * <code>DIR_SBH = 2;</code>
     */
    public static final int DIR_SBH_VALUE = 2;
    /**
     * <pre>
     * 不存在缺口
     * </pre>
     *
     * <code>QK_N = -3;</code>
     */
    public static final int QK_N_VALUE = -3;
    /**
     * <pre>
     *存在缺口
     * </pre>
     *
     * <code>QK_Y = 3;</code>
     */
    public static final int QK_Y_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static DirEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static DirEnum forNumber(int value) {
      switch (value) {
        case 0: return DIR_0;
        case 1: return DIR_UP;
        case -1: return DIR_DN;
        case -2: return DIR_XBH;
        case 2: return DIR_SBH;
        case -3: return QK_N;
        case 3: return QK_Y;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DirEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DirEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DirEnum>() {
            public DirEnum findValueByNumber(int number) {
              return DirEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ChanEnum.getDescriptor().getEnumTypes().get(0);
    }

    private static final DirEnum[] VALUES = values();

    public static DirEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DirEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xyz.redtorch.pb.DirEnum)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027core_enum_chanlun.proto\022\017xyz.redtorch." +
      "pb*u\n\007DirEnum\022\t\n\005DIR_0\020\000\022\n\n\006DIR_UP\020\001\022\023\n\006" +
      "DIR_DN\020\377\377\377\377\377\377\377\377\377\001\022\024\n\007DIR_XBH\020\376\377\377\377\377\377\377\377\377\001\022" +
      "\013\n\007DIR_SBH\020\002\022\021\n\004QK_N\020\375\377\377\377\377\377\377\377\377\001\022\010\n\004QK_Y\020" +
      "\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
