// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: w3_core_enum.proto

package w3.exchange.pb;

public final class W3CoreEnum {
  private W3CoreEnum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * ProductClassEnum是一个产品类型类型
   * </pre>
   *
   * Protobuf enum {@code w3.exchange.pb.ProductClassEnum}
   */
  public enum ProductClassEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知
     * </pre>
     *
     * <code>UnknownProductClass = 0;</code>
     */
    UnknownProductClass(0),
    /**
     * <pre>
     * 币币
     * </pre>
     *
     * <code>SPOT = 1;</code>
     */
    SPOT(1),
    /**
     * <pre>
     * 币币杠杆
     * </pre>
     *
     * <code>MARGIN = 2;</code>
     */
    MARGIN(2),
    /**
     * <pre>
     * 永续合约
     * </pre>
     *
     * <code>SWAP = 3;</code>
     */
    SWAP(3),
    /**
     * <pre>
     * 交割合约
     * </pre>
     *
     * <code>FUTURES = 4;</code>
     */
    FUTURES(4),
    /**
     * <pre>
     * 期权
     * </pre>
     *
     * <code>OPTION = 5;</code>
     */
    OPTION(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 未知
     * </pre>
     *
     * <code>UnknownProductClass = 0;</code>
     */
    public static final int UnknownProductClass_VALUE = 0;
    /**
     * <pre>
     * 币币
     * </pre>
     *
     * <code>SPOT = 1;</code>
     */
    public static final int SPOT_VALUE = 1;
    /**
     * <pre>
     * 币币杠杆
     * </pre>
     *
     * <code>MARGIN = 2;</code>
     */
    public static final int MARGIN_VALUE = 2;
    /**
     * <pre>
     * 永续合约
     * </pre>
     *
     * <code>SWAP = 3;</code>
     */
    public static final int SWAP_VALUE = 3;
    /**
     * <pre>
     * 交割合约
     * </pre>
     *
     * <code>FUTURES = 4;</code>
     */
    public static final int FUTURES_VALUE = 4;
    /**
     * <pre>
     * 期权
     * </pre>
     *
     * <code>OPTION = 5;</code>
     */
    public static final int OPTION_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ProductClassEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ProductClassEnum forNumber(int value) {
      switch (value) {
        case 0: return UnknownProductClass;
        case 1: return SPOT;
        case 2: return MARGIN;
        case 3: return SWAP;
        case 4: return FUTURES;
        case 5: return OPTION;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ProductClassEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ProductClassEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProductClassEnum>() {
            public ProductClassEnum findValueByNumber(int number) {
              return ProductClassEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return W3CoreEnum.getDescriptor().getEnumTypes().get(0);
    }

    private static final ProductClassEnum[] VALUES = values();

    public static ProductClassEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ProductClassEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:w3.exchange.pb.ProductClassEnum)
  }

  /**
   * <pre>
   * CurrencyEnum是一个货币类型
   * </pre>
   *
   * Protobuf enum {@code w3.exchange.pb.CurrencyEnum}
   */
  public enum CurrencyEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知
     * </pre>
     *
     * <code>UnknownCurrency = 0;</code>
     */
    UnknownCurrency(0),
    /**
     * <pre>
     * 美元稳定币
     * </pre>
     *
     * <code>USDT = 1;</code>
     */
    USDT(1),
    /**
     * <pre>
     * 币安稳定币
     * </pre>
     *
     * <code>BUSD = 2;</code>
     */
    BUSD(2),
    /**
     * <pre>
     * 去中心化稳定币
     * </pre>
     *
     * <code>USDC = 3;</code>
     */
    USDC(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 未知
     * </pre>
     *
     * <code>UnknownCurrency = 0;</code>
     */
    public static final int UnknownCurrency_VALUE = 0;
    /**
     * <pre>
     * 美元稳定币
     * </pre>
     *
     * <code>USDT = 1;</code>
     */
    public static final int USDT_VALUE = 1;
    /**
     * <pre>
     * 币安稳定币
     * </pre>
     *
     * <code>BUSD = 2;</code>
     */
    public static final int BUSD_VALUE = 2;
    /**
     * <pre>
     * 去中心化稳定币
     * </pre>
     *
     * <code>USDC = 3;</code>
     */
    public static final int USDC_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static CurrencyEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static CurrencyEnum forNumber(int value) {
      switch (value) {
        case 0: return UnknownCurrency;
        case 1: return USDT;
        case 2: return BUSD;
        case 3: return USDC;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CurrencyEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CurrencyEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CurrencyEnum>() {
            public CurrencyEnum findValueByNumber(int number) {
              return CurrencyEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return W3CoreEnum.getDescriptor().getEnumTypes().get(1);
    }

    private static final CurrencyEnum[] VALUES = values();

    public static CurrencyEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CurrencyEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:w3.exchange.pb.CurrencyEnum)
  }

  /**
   * <pre>
   * ExchangeEnum是一个交易所类型
   * </pre>
   *
   * Protobuf enum {@code w3.exchange.pb.ExchangeEnum}
   */
  public enum ExchangeEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知
     * </pre>
     *
     * <code>UnknownExchange = 0;</code>
     */
    UnknownExchange(0),
    /**
     * <pre>
     * 币安交易所
     * </pre>
     *
     * <code>BINANCE = 1;</code>
     */
    BINANCE(1),
    /**
     * <pre>
     * 欧易交易所
     * </pre>
     *
     * <code>OKX = 2;</code>
     */
    OKX(2),
    /**
     * <pre>
     * 芝麻开门交易所
     * </pre>
     *
     * <code>GATE = 3;</code>
     */
    GATE(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 未知
     * </pre>
     *
     * <code>UnknownExchange = 0;</code>
     */
    public static final int UnknownExchange_VALUE = 0;
    /**
     * <pre>
     * 币安交易所
     * </pre>
     *
     * <code>BINANCE = 1;</code>
     */
    public static final int BINANCE_VALUE = 1;
    /**
     * <pre>
     * 欧易交易所
     * </pre>
     *
     * <code>OKX = 2;</code>
     */
    public static final int OKX_VALUE = 2;
    /**
     * <pre>
     * 芝麻开门交易所
     * </pre>
     *
     * <code>GATE = 3;</code>
     */
    public static final int GATE_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ExchangeEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ExchangeEnum forNumber(int value) {
      switch (value) {
        case 0: return UnknownExchange;
        case 1: return BINANCE;
        case 2: return OKX;
        case 3: return GATE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ExchangeEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ExchangeEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ExchangeEnum>() {
            public ExchangeEnum findValueByNumber(int number) {
              return ExchangeEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return W3CoreEnum.getDescriptor().getEnumTypes().get(2);
    }

    private static final ExchangeEnum[] VALUES = values();

    public static ExchangeEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ExchangeEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:w3.exchange.pb.ExchangeEnum)
  }

  /**
   * <pre>
   * Bar周期
   * </pre>
   *
   * Protobuf enum {@code w3.exchange.pb.BarCycleEnum}
   */
  public enum BarCycleEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>B_5Sec = 0;</code>
     */
    B_5Sec(0),
    /**
     * <code>B_1Min = 1;</code>
     */
    B_1Min(1),
    /**
     * <code>B_3Min = 2;</code>
     */
    B_3Min(2),
    /**
     * <code>B_5Min = 3;</code>
     */
    B_5Min(3),
    /**
     * <code>B_15Min = 4;</code>
     */
    B_15Min(4),
    /**
     * <code>B_30Min = 5;</code>
     */
    B_30Min(5),
    /**
     * <code>B_1H = 6;</code>
     */
    B_1H(6),
    /**
     * <code>B_2H = 7;</code>
     */
    B_2H(7),
    /**
     * <code>B_4H = 8;</code>
     */
    B_4H(8),
    /**
     * <code>B_6H = 9;</code>
     */
    B_6H(9),
    /**
     * <code>B_8H = 10;</code>
     */
    B_8H(10),
    /**
     * <code>B_12H = 11;</code>
     */
    B_12H(11),
    /**
     * <code>B_1Day = 12;</code>
     */
    B_1Day(12),
    /**
     * <code>B_3Day = 13;</code>
     */
    B_3Day(13),
    /**
     * <code>B_1W = 14;</code>
     */
    B_1W(14),
    /**
     * <code>B_1M = 15;</code>
     */
    B_1M(15),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>B_5Sec = 0;</code>
     */
    public static final int B_5Sec_VALUE = 0;
    /**
     * <code>B_1Min = 1;</code>
     */
    public static final int B_1Min_VALUE = 1;
    /**
     * <code>B_3Min = 2;</code>
     */
    public static final int B_3Min_VALUE = 2;
    /**
     * <code>B_5Min = 3;</code>
     */
    public static final int B_5Min_VALUE = 3;
    /**
     * <code>B_15Min = 4;</code>
     */
    public static final int B_15Min_VALUE = 4;
    /**
     * <code>B_30Min = 5;</code>
     */
    public static final int B_30Min_VALUE = 5;
    /**
     * <code>B_1H = 6;</code>
     */
    public static final int B_1H_VALUE = 6;
    /**
     * <code>B_2H = 7;</code>
     */
    public static final int B_2H_VALUE = 7;
    /**
     * <code>B_4H = 8;</code>
     */
    public static final int B_4H_VALUE = 8;
    /**
     * <code>B_6H = 9;</code>
     */
    public static final int B_6H_VALUE = 9;
    /**
     * <code>B_8H = 10;</code>
     */
    public static final int B_8H_VALUE = 10;
    /**
     * <code>B_12H = 11;</code>
     */
    public static final int B_12H_VALUE = 11;
    /**
     * <code>B_1Day = 12;</code>
     */
    public static final int B_1Day_VALUE = 12;
    /**
     * <code>B_3Day = 13;</code>
     */
    public static final int B_3Day_VALUE = 13;
    /**
     * <code>B_1W = 14;</code>
     */
    public static final int B_1W_VALUE = 14;
    /**
     * <code>B_1M = 15;</code>
     */
    public static final int B_1M_VALUE = 15;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static BarCycleEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static BarCycleEnum forNumber(int value) {
      switch (value) {
        case 0: return B_5Sec;
        case 1: return B_1Min;
        case 2: return B_3Min;
        case 3: return B_5Min;
        case 4: return B_15Min;
        case 5: return B_30Min;
        case 6: return B_1H;
        case 7: return B_2H;
        case 8: return B_4H;
        case 9: return B_6H;
        case 10: return B_8H;
        case 11: return B_12H;
        case 12: return B_1Day;
        case 13: return B_3Day;
        case 14: return B_1W;
        case 15: return B_1M;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BarCycleEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        BarCycleEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BarCycleEnum>() {
            public BarCycleEnum findValueByNumber(int number) {
              return BarCycleEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return W3CoreEnum.getDescriptor().getEnumTypes().get(3);
    }

    private static final BarCycleEnum[] VALUES = values();

    public static BarCycleEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private BarCycleEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:w3.exchange.pb.BarCycleEnum)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022w3_core_enum.proto\022\016w3.exchange.pb*d\n\020" +
      "ProductClassEnum\022\027\n\023UnknownProductClass\020" +
      "\000\022\010\n\004SPOT\020\001\022\n\n\006MARGIN\020\002\022\010\n\004SWAP\020\003\022\013\n\007FUT" +
      "URES\020\004\022\n\n\006OPTION\020\005*A\n\014CurrencyEnum\022\023\n\017Un" +
      "knownCurrency\020\000\022\010\n\004USDT\020\001\022\010\n\004BUSD\020\002\022\010\n\004U" +
      "SDC\020\003*C\n\014ExchangeEnum\022\023\n\017UnknownExchange" +
      "\020\000\022\013\n\007BINANCE\020\001\022\007\n\003OKX\020\002\022\010\n\004GATE\020\003*\301\001\n\014B" +
      "arCycleEnum\022\n\n\006B_5Sec\020\000\022\n\n\006B_1Min\020\001\022\n\n\006B" +
      "_3Min\020\002\022\n\n\006B_5Min\020\003\022\013\n\007B_15Min\020\004\022\013\n\007B_30" +
      "Min\020\005\022\010\n\004B_1H\020\006\022\010\n\004B_2H\020\007\022\010\n\004B_4H\020\010\022\010\n\004B" +
      "_6H\020\t\022\010\n\004B_8H\020\n\022\t\n\005B_12H\020\013\022\n\n\006B_1Day\020\014\022\n" +
      "\n\006B_3Day\020\r\022\010\n\004B_1W\020\016\022\010\n\004B_1M\020\017b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
